#! /usr/bin/perl
#
# Copyright (c) 2017-2021 AT&T Intellectual Property.
# Copyright (c) 2015-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

use strict;
use warnings;
use Getopt::Long;

use lib "/opt/vyatta/share/perl5/";
use Vyatta::SNMPMisc;

sub show_view {
    print("\n\nSNMP Views:\n\n");

    foreach my $view ( listNodes( "", "view", "tagnode" ) ) {
        print "View : $view\nOIDs :\n";
        foreach my $oid ( listNodes( "view $view", "oid", "tagnode" ) ) {
            my $exclude = '';
            $exclude = ' exclude'
              if ( isExists("view $view oid $oid exclude") );
            my $mask = '';
            if ( isExists("view $view oid $oid mask") ) {
                my $value = returnValue( "view $view oid $oid", "mask" );
                $mask = " mask $value";
            }
            print "       .$oid$exclude$mask\n";
        }
        print "\n";
    }
}

show_view();

